import { chromium } from 'playwright';
const browser = await chromium.launch();
const page = await browser.newPage({ viewport: { width: 1512, height: 900 } });
await page.goto('http://localhost:3000/', { waitUntil: 'networkidle' });
await page.waitForTimeout(800);
const out = [];
out.push('start: ' + new URL(page.url()).pathname);
await page.getByText('Virtual tags', { exact: true }).first().click();
await page.waitForURL('**/virtual-tags'); await page.waitForTimeout(600);
out.push('after click Virtual tags: ' + new URL(page.url()).pathname);
await page.getByText('Anomalies', { exact: true }).first().click();
await page.waitForURL('**/anomalies'); await page.waitForTimeout(600);
out.push('after click Anomalies: ' + new URL(page.url()).pathname);
await page.screenshot({ path: process.argv[2] });
await page.getByText('Overview', { exact: true }).first().click();
await page.waitForURL('http://localhost:3000/'); await page.waitForTimeout(400);
out.push('after click Overview: ' + new URL(page.url()).pathname);
console.log(out.join('\n'));
await browser.close();
